export const clamp = (value, min, max) => Math.min(Math.max(value, min), max);
export const pxiMetricDefinitions = [
    {
        id: 'hyOas',
        label: 'High Yield OAS',
        lowerBound: 0.02,
        upperBound: 0.06,
        weight: 1.2,
        polarity: -1,
        unit: 'percent',
    },
    {
        id: 'igOas',
        label: 'Investment Grade OAS',
        lowerBound: 0.01,
        upperBound: 0.03,
        weight: 1,
        polarity: -1,
        unit: 'percent',
    },
    {
        id: 'vix',
        label: 'VIX Volatility',
        lowerBound: 12,
        upperBound: 35,
        weight: 0.9,
        polarity: -1,
        unit: 'index',
    },
    {
        id: 'u3',
        label: 'U-3 Unemployment',
        lowerBound: 0.035,
        upperBound: 0.08,
        weight: 0.7,
        polarity: -1,
        unit: 'ratio',
    },
    {
        id: 'usd',
        label: 'USD Index (DXY)',
        lowerBound: 90,
        upperBound: 110,
        weight: 0.6,
        polarity: 1,
        unit: 'index',
    },
    {
        id: 'nfci',
        label: 'Chicago Fed NFCI',
        lowerBound: -0.5,
        upperBound: 1,
        weight: 0.8,
        polarity: -1,
        unit: 'index',
    },
    {
        id: 'btcReturn',
        label: 'BTC Daily Return',
        lowerBound: -0.05,
        upperBound: 0.05,
        weight: 0.5,
        polarity: 1,
        unit: 'ratio',
    },
];
export const pxiBands = [
    { label: 'Stress', min: 0, max: 30, color: '#FF5A5F' },
    { label: 'Caution', min: 30, max: 50, color: '#F59E0B' },
    { label: 'Stable', min: 50, max: 75, color: '#22C55E' },
    { label: 'PAMP', min: 75, max: 100, color: '#A78BFA' },
];
